note-edit(1)

# NAME

note-edit - open a note in your text editor

# SYNOPSIS

note edit [options] [FILTER ...]

# DESCRIPTION

Select a note that matches the filter criteria and open it in your text editor.

# OPTIONS

*positional arguments*

	*FILTER*
		tag or text based search terms

*optional arguments*

	*-fulltext* 
		perform full text search instead of key comparision

# EXAMPLES
```
# edit a note called fuubar
note edit fuubar
```
