note-config(1)

# NAME

note-config - configuration management

# SYNOPSIS

note config [get | set | show]

# DESCRIPTION

Modify the note configuration file

# OPTIONS

*positional arguments*

	*get*
		get a certain configuration value

	*set*
		set a certain configuration value

	*show*
		show all of the configuration with defaults


# EXAMPLES

```
# show the configured state directory
note config get state_dir
```
